services:
  mpp-solar:
    build: ./mppsolar/
    volumes:
      - app-solar-config:/etc/mpp-solar
    tmpfs:
      - /run
      - /sys/fs/cgroup
      - /tmp
    depends_on:
      - telegraf
    environment:
      - MOXA_CONNECTION_STRING=tcp:192.168.0.9:4001
    ports:
      - 4001:4001
    healthcheck:
      test: "pidof socat && pidof python || exit 1"
      interval: 20s
      timeout: 1s
      retries: 1
      start_period: 10s
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana.home.arpa
      - VIRTUAL_PORT=3000
    depends_on:
      - influxdb
    restart: unless-stopped
    user: "0"
  
  telegraf:
    image: telegraf:1.23.2
    volumes:
      - telegraf_config:/etc/telegraf
    depends_on:
      - influxdb
      - mqtt
    entrypoint: telegraf --config-directory /etc/telegraf/telegraf.d
    restart: unless-stopped

  influxdb:
    image: influxdb:2.3
    volumes:
      - influx_config:/etc/influxdb2
      - influx_data:/var/lib/influxdb2
    ports:
      - 8086:8086
    expose:
      - "8086"
    environment:
      - VIRTUAL_HOST=influx.home.arpa
      - VIRTUAL_PORT=8086
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - mosquito:/mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
    
volumes:
  mosquito:
    external: true
  influx_config:
    external: true
  influx_data:
    external: true
  telegraf_config:
    external: true
  grafana_data:
    external: true
  app-solar-config:
    external: true
