services:
  mpp-solar:
    build: ./mppsolar/
    volumes:
      - app-solar-config:/etc/mpp-solar
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - telegraf
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
  
  telegraf:
    image: telegraf:1.23.2
    volumes:
      - telegraf_config:/etc/telegraf
    depends_on:
      - influxdb
      - mqtt
    
  influxdb:
    image: influxdb:2.3
    volumes:
      - influx_config:/etc/influxdb2
      - influx_data:/var/lib/influxdb2
    ports:
      - 8086:8086

  mqtt:
    image: eclipse-mosquitto:latest
    volumes:
      - mosquito:/mosquitto
      
volumes:
  mosquito:
    external: true
  influx_config:
    external: true
  influx_data:
    external: true
  telegraf_config:
    external: true
  grafana:
    external: true