version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - traefik-net
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer0.entrypoints=web
      - traefik.http.routers.portainer0.rule=Host(`portainer.home.arpa`)
      - traefik.http.routers.portainer0.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.services.portainer.loadbalancer.server.scheme=http
      - traefik.http.routers.portainer0.middlewares=portainer-redirect
      - traefik.http.middlewares.portainer-redirect.redirectscheme.scheme=https
      - traefik.http.routers.portainer1.entrypoints=websecure
      - traefik.http.routers.portainer1.rule=Host(`portainer.home.arpa`)
      - traefik.http.routers.portainer1.tls=true
      - traefik.http.routers.portainer1.tls.certresolver=myresolver
      - traefik.http.routers.portainer1.service=portainer
      - traefik.docker.network=traefik-net
    restart: always

volumes:
  portainer_data:
    external: true

networks:
  traefik-net:
    external: true