version: '3.9'

services:

  db:
    image: postgres
    restart: always
    networks:
      - postgres-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.entrypoints=web
      - traefik.http.routers.adminer.service=adminer
      - traefik.http.routers.adminer.rule=Host(`adminer.home.arpa`)
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.services.adminer.loadbalancer.server.scheme=http

      - traefik.http.routers.adminer.middlewares=adminer-redirect
      - traefik.http.middlewares.portainer-redirect.redirectscheme.scheme=https
      
      - traefik.http.routers.adminer1.entrypoints=websecure
      - traefik.http.routers.adminer1.rule=Host(`adminer.home.arpa`)
      - traefik.http.routers.adminer1.tls=true
      - traefik.http.routers.adminer1.tls.certresolver=myresolver
      - traefik.http.routers.adminer1.service=adminer

      - traefik.docker.network=traefik-net
    networks:
      - traefik-net
      - postgres-net
    restart: always

networks:
  postgres-net:
    external: true

  traefik-net:
    external: true

volumes:
  postgres:
    external: yes
